# Generated by Django 5.2 on 2026-03-09 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_backfill_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('week_starts_on', models.CharField(choices=[('monday', 'Monday'), ('sunday', 'Sunday')], default='monday', max_length=10)),
                ('pomodoro_work_minutes', models.PositiveIntegerField(default=25)),
                ('pomodoro_short_break_minutes', models.PositiveIntegerField(default=5)),
                ('pomodoro_long_break_minutes', models.PositiveIntegerField(default=15)),
                ('pomodoros_before_long_break', models.PositiveIntegerField(default=4)),
                ('daily_work_goal_hours', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
                ('daily_study_goal_hours', models.DecimalField(decimal_places=1, default=4.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
