# Generated by Django 5.2

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_create_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="pomodoro_work_minutes",
            field=models.PositiveIntegerField(
                default=25,
                validators=[django.core.validators.MaxValueValidator(480)],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="pomodoro_short_break_minutes",
            field=models.PositiveIntegerField(
                default=5,
                validators=[django.core.validators.MaxValueValidator(480)],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="pomodoro_long_break_minutes",
            field=models.PositiveIntegerField(
                default=15,
                validators=[django.core.validators.MaxValueValidator(480)],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="pomodoros_before_long_break",
            field=models.PositiveIntegerField(
                default=4,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="daily_work_goal_hours",
            field=models.DecimalField(
                decimal_places=1,
                default=8.0,
                max_digits=4,
                validators=[django.core.validators.MaxValueValidator(24)],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="daily_study_goal_hours",
            field=models.DecimalField(
                decimal_places=1,
                default=4.0,
                max_digits=4,
                validators=[django.core.validators.MaxValueValidator(24)],
            ),
        ),
    ]
