# Generated by Django 5.2.17 on 2026-09-26 22:21

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_max_value_validators_to_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='block_reminder_minutes',
            field=models.PositiveSmallIntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shutdown_reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(condition=models.Q(('block_reminder_minutes__isnull', True), ('block_reminder_minutes__range', (1, 120)), _connector='OR'), name='block_reminder_minutes_1_to_120_or_null'),
        ),
    ]
