# Generated by Django 5.2 on 2026-03-01 01:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#6366f1', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex color (e.g. #ff0000)', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='kanban_status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], db_index=True, default='todo', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='scheduled_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
