# Generated by Django 5.2 on 2026-03-05 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_classschedule'),
        ('tasks', '0006_task_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeblock',
            name='study_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='study.studyblock'),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='tasks.task'),
        ),
    ]
