# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
