# Generated by Django 5.2.17 on 2026-09-27 12:37

import datetime
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_holidays_cancellations'),
        ('tasks', '0011_task_remind_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRecurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('freq', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('starts_on', models.DateField()),
                ('until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='is_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='occurrence_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='tasks.task'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('series', 'occurrence_date'), name='task_one_row_per_series_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('occurrence_date__isnull', True), ('series__isnull', True)), models.Q(('occurrence_date__isnull', False), ('series__isnull', False)), _connector='OR'), name='task_series_and_occurrence_date_together'),
        ),
        migrations.AddField(
            model_name='taskrecurrence',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence', to='tasks.task'),
        ),
        migrations.AddConstraint(
            model_name='taskrecurrence',
            constraint=models.CheckConstraint(condition=models.Q(('interval__gte', 1), ('interval__lte', 30)), name='taskrecurrence_interval_1_to_30'),
        ),
        migrations.AddConstraint(
            model_name='taskrecurrence',
            constraint=models.CheckConstraint(condition=models.Q(('until__isnull', True), ('until__gte', django.db.models.expressions.CombinedExpression(models.F('starts_on'), '-', models.Value(datetime.timedelta(days=1)))), _connector='OR'), name='taskrecurrence_until_not_before_start'),
        ),
    ]
