# Generated by Django 5.2 on 2026-01-29 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('focus', 'Focus'), ('short_break', 'Short Break'), ('long_break', 'Long Break')], default='focus', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=25)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pomodoro_sessions', to='tasks.task')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
