# Generated by Django 5.2 on 2026-03-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorosession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
