# Generated by Django 5.2.17 on 2026-09-26 13:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0003_add_user_to_pomodoro_session'),
        ('tasks', '0010_timeblock_session_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorosession',
            name='time_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pomodoro_sessions', to='tasks.timeblock'),
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='started_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
