# Generated by Django 5.2.17 on 2026-09-27 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_classschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='rotation_weeks_on',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='semester',
            name='rotation_anchor',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='rotation_weeks',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.CheckConstraint(condition=models.Q(('rotation_weeks__gte', 1), ('rotation_weeks__lte', 4)), name='semester_rotation_weeks_range'),
        ),
    ]
