# Generated by Django 5.2.17 on 2026-09-26 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreview',
            name='energy',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='dailyreview',
            constraint=models.CheckConstraint(condition=models.Q(('energy__isnull', True), models.Q(('energy__gte', 1), ('energy__lte', 3)), _connector='OR'), name='dailyreview_energy_1_to_3'),
        ),
    ]
